version: "3.1"

services:
  rport:
    build:
      context:  ./rport
    command: [ "--auth", "yusuf:pass" ]
    ports:
      - 127.0.0.1:8085:8080
      - 127.0.0.1:3001:3000
    # volumes:
    #   - ./rport-lib:/var/lib/rport

networks:
  default:
    name: app-net
    external: true